### ISSUE TITLE
[Opinion]: 新增自动项目类型

### ISSUE THREAD

**Issue by lastsummerx** [NEKOparapa/AiNiee#545]
### 意见/建议内容

1. 新增自动项目类型
   能根据目录下文件类型自动读写。
2. 兼容插件
   目前看插件MToolOptimizer和SpecialTextFilter用到了project_type，为了兼容插件要对cache做如下改动
    1. CacheItem新增属性 file_project_type（文件实际的项目类型） 用于标识实际的项目类型
    2. CacheProject新增属性 file_project_types （输入文件夹下实际包含的项目类型） 用于在插件中快速过滤出对应的项目类型
3. 新增排除目录/文件的设置
    排除掉一些不希望读取的文件或目录

### 为什么需要这个功能或修改？

目录下存在多种不同类型的文档时就不需要切换了，cache也不用担心被覆盖

### 补充信息

有一点没想好就是，当目录很大时，增量插件是在读取文件之后执行，依然会把目录下的所有文件又都读一遍，可能会比较慢

**Comment by NEKOparapa** [comment]
> ### 意见/建议内容
> 1. 新增自动项目类型
>    能根据目录下文件类型自动读写。


是指在项目类型里面加个“自动识别项目”选项么？

**Comment by NEKOparapa** [comment]
我觉得可以的，是需要这个功能的

**Comment by NEKOparapa** [comment]
做的时候，要考虑一下。数据文件的检验分类方法，可以方便扩展和增加。比如说json文件，现在就已经支持三种格式了，后面我还会加个i18next类型。还有表格文件，现在只支持t++导出的双列格式，后面我可能会加个其他排列格式的表格支持。

**Comment by lastsummerx** [comment]
> > ### 意见/建议内容
> > 
> > 1. 新增自动项目类型
> >    可以根据目录下文件类型自动读写器。
> 
> 是指在项目类型里面加个“自动识别项目”选项吗？

是这个意思，文件后缀相同会考虑读文件内容来区分是什么类型

**Comment by lastsummerx** [comment]
1. 自动识别文件类型后，如果目录下同时存在文本文件和非文本文件，且非文本文件占多数，如docx，在检测编码detect_file_encoding时，会得出non_text/xxx的编码。而写入文本文件是按照检测出的编码写的，导致按non_text/xxx编码写入文本文件失败。
2. 像docx和epub就不是用检测的编码，不知道是忘了改还是故意没改。
3. 而且检测编码应该是具体reader的行为吧，像现在是直接读二进制检测，对于docx、epub检测为non_text/xxx也没用吧

**Comment by NEKOparapa** [comment]
对，编码检查功能，我昨晚和@nekomiya-hinata聊了聊这方面的改进，也都赞同把编码检查功能放进reader里面，变成一文件一编码，还有可能增加原文语言识别功能，一文件一语言，为后面自动识别原文语言功能铺路

**Comment by NEKOparapa** [comment]
现在你要进行的改进和他进行的改进应该有冲突，可以共享一下进度和想法

**Comment by lastsummerx** [comment]
这个opinion主要是做提的内容，如果有其他大的改动会另外提opinion。初步是解决报错的问题，会在计数里去除non_text/xxx。

**Comment by lastsummerx** [comment]
> 现在你要进行的改进和他进行的改进应该有冲突，可以共享一下进度和想法。我觉得你的改进会多些，影响到整个读写器模块，你在重构时留个检测功能接口，方便后续改进就行

如果是想法的话
1. 把纯文本的检测放到basesourcereader里，纯文本的子类都不用再写一遍
2. docx、epub重载方法，解压出来做纯文本检测就行，可以在fileaccessor加一个检测的函数
3. 如果后续考虑做原？编码输出，可以作为cacheitem的属性

**Comment by nekomiya-hinata** [comment]
原始编码和可能的文件语言的话，我想的是在`CacheProject`中加一个`file_prop`属性去存
key是文件路径或者文件名，value为是否为文本，对应的编码以及原始语言

**Comment by NEKOparapa** [comment]
> 原始编码和可能的文件语言的话，我想的是在`CacheProject`中加一个`file_prop`属性去存 key是文件路径或者文件名，value为是否为文本，对应的编码以及原始语言
> 
> 在每一个`cacheitem`都加感觉有点重复

现在的cacheitem里的file_name，storage_path字段也在重复，我觉得再加一两个字段也无所谓了，这样写起来更简便些。

**Comment by lastsummerx** [comment]
如果是参照实际情况，一个项目对应一个目录，一个目录有多个文件，一个文件有多行原文。
那么应该是CacheProject包含多个CacheFile，CacheFile包含多个CacheItem，CacheFile放文件的属性，只是这样对缓存改动大。然后这里的CacheFile会不会是一个目录就不清楚了，至少目前不是。

**Comment by lastsummerx** [comment]
文件编码又发现一个新的问题，纯英文会被检测成ascii，如果占多数会导致中文无法写入

**Comment by NEKOparapa** [comment]
因为要进行自动识别文件类型，输入文件夹可能有混合文件类型，文件信息都要独立化存储。我有个想法是，改进一下现在的缓存结构，文本对按文件进行分类，改成类似json结构：

```yaml
  # --- 文件: data/Actors.json ---
  "data/Actors.json":

    - language "xxxx"                 # 文件语言
      coder: "xxx"                 # 编码格式
      filename: ""                  # 文件名字


    - id: "xxxx"                 # ID 1
      source: "xxx"                 # 原文1
      translation: ""                  # 译文2


    - id: "xxxx"                 # ID 2
      source: "xxx"                 # 原文1
      translation: ""                  # 译文2

```
